import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					React Query Pagination and Infinite Queries with NextJs
				</h1>
				<br />
				<h2>Pagination SSR</h2>
				<Link href="/paginationSSR">Pagination SSR</Link>
				<br />
				<br />
				<h2>Infinite Queries SSR</h2>
				<Link href="/infiniteQueriesSSR">Infinite Queries SSR</Link>
			</main>
		</div>
	);
}
